### ISSUE TITLE
2.1.0 Changes

### ISSUE THREAD

**Issue by akifo** [akifo/vue-memo#8]
## General Notes

- It's a completely different new vue-memo

## New Firebase Model

```
{
  "users": {
    "$uid": {
      "name": "tanaka",
      "memos": {
        "-Kr22TiTi4ktLiDrE9FM": true,
        "-Kr5EWkDqs_d63gutnKv": true
      }
    }
  },
  "memos": {
    "$mid": {
      "memoName": "awesome-orange",
      "title": "aaaa",
      "body": "bbbb",
      "authorID": "$uid",
      "created": 1502741787796,
      "modified": 1502741787796,
      "starCount": 2,
      "stars": {
        "CLIPLIrf1occ83qNAB5jzE6ukAC2": true,
        "sjhzQ5Jke5QsLH1vaDjPrPl5BSs2": true
      }
    }
  }
}
```

### TODO

- [ ] index speed test
  - [ ] sort by created
  - [ ] sort by starCount
  - [ ] multiple fetch (If we display 20 latest memos, we have to fetch from users 20 times)
